server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/marur
spring.datasource.username=postgres
spring.datasource.password=Sena2020

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

spring.application.name=marur-backend

jwt.secret=marur2024secretkey_must_be_at_least_32_characters_long
jwt.expiration=86400000

wompi.public-key=pub_test_tu_llave_publica
wompi.private-key=prv_test_tu_llave_privada
wompi.events-key=test_events_tu_llave
wompi.redirect-url=http://localhost:4200/payment/result